version: '3'
services:
  #api:
  #  build:
  #    dockerfile: Dockerfile
  #  ports:
  #    - "9000:9000"
  #  container_name: node-server
  #  volumes:
  #     - ./ngrx-course:/usr/src/app/ngrx-course
  #     - /usr/src/app/ngrx-course/node_modules
  #  command:
  #      bash -c "npm install && npm run server"
  angular-ui:
    build:
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-client
    volumes:
       - ./ngrx-course:/usr/src/app
       #- /usr/src/app/node_modules
    command:
        sh -c "npm install && npm start"